version: "3.9"
services:
 postgres:
  image: postgres:14-alpine
  container_name: postgres
  restart: unless-stopped
  environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  ports:
    - 5432:5432
  volumes:
    - ~/postgres/data/:/var/lib/postgresql/data # mkdir -p ~/apps/redis/data/